In [1]:

from pymongo import MongoClient
from datetime import datetime, timedelta
import pandas as pd
import xarray
import os

In [2]:
from pymongo.collection import Collection#

def get_timeseries_df(
        location : str,
        date : datetime,
        matching : dict,
        projection : dict,
        collection : Collection,
) -> pd.DataFrame:
    """This function retrieves a formatted df from the dabase for a given location and date. 

    The df is formatted to have the following columns: StramFlow and LocationId. The index is the DateTime column.

    Parameters
    ----------
    location : str
        The fews alphanumeric location id for the location (e.g. SMFV2).
    date : datetime
        datetime object for a minimum date to retrieve data for. 
        If data doesn't exist at some point in the range it wont return.
    matching : dict
        The dict by which to match the data in the database. Where your moduleID and stuff like that goes
    projection : dict
        The dict which tells you how the data that you are extracting should be named in the dataframe
        Have to include where your DateTime is coming from and your target
    collection : Collection
        The pymongo collection object from the database to query

    Returns
    -------
    df : pd.DataFrame
        A pandas dataframe with the following column (value based on projection). The index is the DateTime column.

    """
    matching["locationId"] = location
    matching["startTime"] = {"$gte" : date}

    projection["locationId"] = "$locationId"
    projection["_id"] = 0

    it = collection.aggregate([
        {"$match": matching}, 
        {"$sort":{"locationId": 1, "bucket": 1,}},
        {"$unwind": "$timeseries"},
        {"$project": projection}
    ])
    # Make a dataframe from collection iterator
    rows = list(it)
    df = pd.DataFrame(rows)

    #set the correct type for locationId and set the index to DateTime
    df["locationId"] = df["locationId"].astype(str).astype(object)
    df.set_index("DateTime", inplace=True)

    #drop location you already know it
    df = df.drop(columns=["locationId"])
    
    return df

In [3]:
print("hi")

hi

In [4]:
connection_uri = "mongodb://fews_admin:AvjgHB1zgtBS*T#@knxpwmongodb1.main.tva.gov:27017/FEWS_ARCHIVE?authSource=admin&tls=true"
client = MongoClient(connection_uri)

In [5]:
client.list_database_names()

locations = ["SMFV2", "SALV2", "GATV2", "CLVV2", "VSTV2", "SGWN7"]
locations = ["SMFV2"]
date = datetime(1985,1,1, 0,0,0)

In [6]:
db = client["FEWS_ARCHIVE"]
collection = db["ExternalHistoricalScalarTimeSeries"]

location = "SMFV2"
#location = "GATV2"
matching = {"moduleInstanceId": "Preprocess_HG_to_QR", "parameterId": "QR", "qualifierId": "[]", "encodedTimeStepId": "SETS60"}
projection = {"DateTime": "$timeseries.t", "Streamflow": "$timeseries.v"}
#date = datetime(1980,1,1, 0,0,0)
#date = datetime(2017,1,1, 0,0,0)
date = datetime(2001,1,1, 0,0,0)

df_flow = get_timeseries_df(
    location=location,
    date=date,
    matching=matching,
    projection=projection,
    collection=collection
)

matching =  {"moduleInstanceId": "QPE_to_MAP", "parameterId": "MAP", "qualifierId": "[]", "encodedTimeStepId": "SETS60"}
projection = {"DateTime": "$timeseries.t", "MAP": "$timeseries.v"}

df_map = get_timeseries_df(
    location=location,
    date=date,
    matching=matching,
    projection=projection,
    collection=collection,
)

print(df_map)
print(df_flow)

#combined = df_flow.join(df_map.drop(columns=["locationId"]), how="left")
combined = df_flow.join(df_map, how="left")
print(df_flow)
combined

#fname = "timeseries_" + location + ".nc"
fname = location + ".nc"
#os.remove(fname) if os.path.exists(fname) else None
xa = xarray.Dataset.from_dataframe(combined)
xa.to_netcdf(fname)

                     MAP
DateTime
2001-01-01 00:00:00  0.0
2001-01-01 01:00:00  0.0
2001-01-01 02:00:00  0.0
2001-01-01 03:00:00  0.0
2001-01-01 04:00:00  0.0
...                  ...
2026-07-27 09:00:00  0.0
2026-07-27 10:00:00  0.0
2026-07-27 11:00:00  0.0
2026-07-27 12:00:00  0.0
2026-07-27 13:00:00  0.0

[224126 rows x 1 columns]
                     Streamflow
DateTime
2001-01-01 00:00:00       0.934
2001-01-01 01:00:00       0.934
2001-01-01 02:00:00       0.934
2001-01-01 03:00:00       0.934
2001-01-01 04:00:00       0.934
...                         ...
2026-07-27 09:00:00       3.838
2026-07-27 10:00:00       3.745
2026-07-27 11:00:00       3.745
2026-07-27 12:00:00       3.745
2026-07-27 13:00:00       3.655

[224126 rows x 1 columns]
                     Streamflow
DateTime
2001-01-01 00:00:00       0.934
2001-01-01 01:00:00       0.934
2001-01-01 02:00:00       0.934
2001-01-01 03:00:00       0.934
2001-01-01 04:00:00       0.934
...                         ...
2026-07-27 09:00:00       3.838
2026-07-27 10:00:00       3.745
2026-07-27 11:00:00       3.745
2026-07-27 12:00:00       3.745
2026-07-27 13:00:00       3.655

[224126 rows x 1 columns]

In [7]:
db = client["FEWS_ARCHIVE"]
collection = db["ExternalHistoricalScalarTimeSeries"]
it = collection.aggregate([
{"$match" : {"moduleInstanceId": "Preprocess_HG_to_QR", "parameterId": "QR", "qualifierId": "[]", "encodedTimeStepId": "SETS60", 
    #"locationId" : {"$in" : ["SMFV2", "SALV2", "GATV2", "CLVV2", "VSTV2", "SGWN7"]} ,
    "locationId" : {"$in" : locations} ,
    "startTime" : {"$gte" : date}
    #"startTime" : {"$gte" : datetime(2018,2,2, 0,0,0)}
    }},
    #"locationId" : {"$in" : ["SMFV2"]} ,"startTime" : {"$gte" : ISODate("2020-01-01 00:00:00.000Z")}}},
{"$sort":{"locationId":1, "bucket":1,}},
{"$unwind" : "$timeseries"},
{"$project" : {"DateTime":"$timeseries.t", "StreamFlow":"$timeseries.v", "_id":0, "locationId":"$locationId"}}
])

#with open("headwater_basins_flow.csv", "w") as f:
    #for r in it:
        #f.write(f"{r['locationId']},{r['t']},{r['v']}\n")

l = list(it)
print(l[0:5])

[{'DateTime': datetime.datetime(2001, 1, 1, 0, 0), 'StreamFlow': 0.9340000152587891, 'locationId': 'SMFV2'}, {'DateTime': datetime.datetime(2001, 1, 1, 1, 0), 'StreamFlow': 0.9340000152587891, 'locationId': 'SMFV2'}, {'DateTime': datetime.datetime(2001, 1, 1, 2, 0), 'StreamFlow': 0.9340000152587891, 'locationId': 'SMFV2'}, {'DateTime': datetime.datetime(2001, 1, 1, 3, 0), 'StreamFlow': 0.9340000152587891, 'locationId': 'SMFV2'}, {'DateTime': datetime.datetime(2001, 1, 1, 4, 0), 'StreamFlow': 0.9340000152587891, 'locationId': 'SMFV2'}]

In [126]:

#db = client["FEWS_ARCHIVE"]
#collection = db["ExternalHistoricalScalarTimeSeries"]
#it = collection.aggregate([
#{"$match" : {"moduleInstanceId": "Preprocess_HG_to_QR", "parameterId": "QR", "qualifierId": "[]", "encodedTimeStepId": "SETS60", 
    ##"locationId" : {"$in" : ["SMFV2", "SALV2", "GATV2", "CLVV2", "VSTV2", "SGWN7"]} ,
    #"locationId" : {"$in" : ["SMFV2"]} ,
    #"startTime" : {"$gte" : datetime(1985,1,1, 0,0,0)}
    ##"startTime" : {"$gte" : datetime(2018,2,2, 0,0,0)}
    #}},
    ##"locationId" : {"$in" : ["SMFV2"]} ,"startTime" : {"$gte" : ISODate("2020-01-01 00:00:00.000Z")}}},
#{"$sort":{"locationId":1, "bucket":1,}},
#{"$unwind" : "$timeseries"},
#{"$project" : {"DateTime":"$timeseries.t", "StreamFlow":"$timeseries.v", "_id":0, "locationId":"$locationId"}}
#])

In [127]:
#print(len(l))
#print(l[0])
df = pd.DataFrame(l)
df['locationId'] = df['locationId'].astype(str).astype(object)
df["DateTime"] = pd.to_datetime(df["DateTime"])
df = df.set_index(["DateTime"])
print(df)
xa = xarray.Dataset.from_dataframe(df)
xa["locationId"] = xa["locationId"].astype(str)
#print(df['locationId'].dtype)
xa.to_netcdf("flow_data.nc")
#print(xa["v"].isnull().sum())

                     StreamFlow locationId
DateTime
1999-01-01 00:00:00       1.331      SMFV2
1999-01-01 01:00:00       1.331      SMFV2
1999-01-01 02:00:00       1.331      SMFV2
1999-01-01 03:00:00       1.359      SMFV2
1999-01-01 04:00:00       1.388      SMFV2
...                         ...        ...
2026-07-24 16:00:00       9.155      SMFV2
2026-07-24 17:00:00       8.802      SMFV2
2026-07-24 18:00:00       8.629      SMFV2
2026-07-24 19:00:00       8.629      SMFV2
2026-07-24 20:00:00       8.459      SMFV2

[241605 rows x 2 columns]

In [128]:
df

                     StreamFlow locationId
DateTime
1999-01-01 00:00:00       1.331      SMFV2
1999-01-01 01:00:00       1.331      SMFV2
1999-01-01 02:00:00       1.331      SMFV2
1999-01-01 03:00:00       1.359      SMFV2
1999-01-01 04:00:00       1.388      SMFV2
...                         ...        ...
2026-07-24 16:00:00       9.155      SMFV2
2026-07-24 17:00:00       8.802      SMFV2
2026-07-24 18:00:00       8.629      SMFV2
2026-07-24 19:00:00       8.629      SMFV2
2026-07-24 20:00:00       8.459      SMFV2

[241605 rows x 2 columns]

In [129]:
import pandas as pd
df = pd.read_csv("headwater_basins_flow.csv", names=["locationId", "t", "v"], index_col=["locationId", "t"])

In [130]:
df.index

MultiIndex([('CLVV2', '1985-01-01 00:00:00'),
            ('CLVV2', '1985-01-01 01:00:00'),
            ('CLVV2', '1985-01-01 02:00:00'),
            ('CLVV2', '1985-01-01 03:00:00'),
            ('CLVV2', '1985-01-01 04:00:00'),
            ('CLVV2', '1985-01-01 05:00:00'),
            ('CLVV2', '1985-01-01 06:00:00'),
            ('CLVV2', '1985-01-01 07:00:00'),
            ('CLVV2', '1985-01-01 08:00:00'),
            ('CLVV2', '1985-01-01 09:00:00'),
            ...
            ('VSTV2', '2026-07-13 10:00:00'),
            ('VSTV2', '2026-07-13 11:00:00'),
            ('VSTV2', '2026-07-13 12:00:00'),
            ('VSTV2', '2026-07-13 13:00:00'),
            ('VSTV2', '2026-07-13 14:00:00'),
            ('VSTV2', '2026-07-13 15:00:00'),
            ('VSTV2', '2026-07-13 16:00:00'),
            ('VSTV2', '2026-07-13 17:00:00'),
            ('VSTV2', '2026-07-13 18:00:00'),
            ('VSTV2', '2026-07-13 19:00:00')],
           names=['locationId', 't'], length=1925739)

In [131]:
collection = db["SimulatedForecastingScalarTimeSeries"]
it = collection.aggregate([
    {"$match": {"parameterId":"QR", 
                "moduleInstanceId": {"$in": ["ADJUSTQ_ALCT1_Forecast","ADJUSTQ_ARTT1_Forecast","ADJUSTQ_AVLN7_Forecast","ADJUSTQ_BARK2E_Forecast","ADJUSTQ_BIGT1_Forecast","ADJUSTQ_BIRN7_Forecast","ADJUSTQ_BLAN7_Forecast","ADJUSTQ_BLTN7_Forecast","ADJUSTQ_BNAA1_Forecast","ADJUSTQ_BRRT1_Forecast","ADJUSTQ_BRVG1_Forecast","ADJUSTQ_BSBA1_Forecast","ADJUSTQ_CAFT1_Forecast","ADJUSTQ_CDZK2_Forecast","ADJUSTQ_CEPN7_Forecast","ADJUSTQ_CHKT1_Forecast","ADJUSTQ_CHSA1_Forecast","ADJUSTQ_CKVT1N_Forecast","ADJUSTQ_CLVV2_Forecast","ADJUSTQ_CNVT1_Forecast","ADJUSTQ_COLT1_Forecast","ADJUSTQ_CTPN7_Forecast","ADJUSTQ_DOET1_Forecast","ADJUSTQ_EMBT1_Forecast","ADJUSTQ_EMGT1_Forecast","ADJUSTQ_ENGG1_Forecast","ADJUSTQ_FLCN7_Forecast","ADJUSTQ_FLTT1_Forecast","ADJUSTQ_FYTT1_Forecast","ADJUSTQ_GATV2_Forecast","ADJUSTQ_GERA1_Forecast","ADJUSTQ_HEPN7_Forecast","ADJUSTQ_HMLT1_Forecast","ADJUSTQ_HORT1_Forecast","ADJUSTQ_HSPN7_Forecast","ADJUSTQ_HWEG1_Forecast","ADJUSTQ_IRCT1_Forecast","ADJUSTQ_IVYN7_Forecast","ADJUSTQ_JNSV2_Forecast","ADJUSTQ_LBVT1_Forecast","ADJUSTQ_LLDT1_Forecast","ADJUSTQ_MARN7_Forecast","ADJUSTQ_MCGT1_Forecast","ADJUSTQ_MCST1_Forecast","ADJUSTQ_MLTT1_Forecast","ADJUSTQ_MYVT1_Forecast","ADJUSTQ_NEEN7_Forecast","ADJUSTQ_NOLT1_Forecast","ADJUSTQ_NRMT1_Forecast","ADJUSTQ_NWPT1_Forecast","ADJUSTQ_OAKT1_Forecast","ADJUSTQ_PLKT1_Forecast","ADJUSTQ_PORT1S_Forecast","ADJUSTQ_PORT1_Forecast","ADJUSTQ_PRTN7_Forecast","ADJUSTQ_PSPT1_Forecast","ADJUSTQ_RLRV2_Forecast","ADJUSTQ_ROSN7_Forecast","ADJUSTQ_RTRN7_Forecast","ADJUSTQ_SALV2_Forecast","ADJUSTQ_SEET1_Forecast","ADJUSTQ_SEVT1_Forecast","ADJUSTQ_SFYV2_Forecast","ADJUSTQ_SGWN7_Forecast","ADJUSTQ_SHVT1_Forecast","ADJUSTQ_SMFV2_Forecast","ADJUSTQ_TAZT1_Forecast","ADJUSTQ_TLRT1_Forecast","ADJUSTQ_TMFT1_Forecast","ADJUSTQ_TWNT1_Forecast","ADJUSTQ_VSTV2_Forecast","ADJUSTQ_WCKG1_Forecast","ADJUSTQ_WDVA1_Forecast","ADJUSTQ_WHTT1_Forecast"]},
                "locationId":{"$in":["SMFV2","SALV2","RLRV2","GATV2","CLVV2","VSTV2","SGWN7"]},
                "encodedTimeStepId":"DTOD_0_6_12_18TZ_CST", "qualifierId":"[\"Adj\"]"}
    },
    {"$sort":{"locationId":1, "forecastTime":1,}},
    {"$unwind" : "$timeseries"},
    { "$match": { "$expr": { "$gte": [ "$timeseries.t", "$forecastTime" ] } } },
    {"$match" : {"$expr" : { "$lte" : [{"$dateDiff" : {"startDate":"$forecastTime", "endDate":"$timeseries.t", "unit":"hour"}}, 168]}}}, 
    {"$project" : {"t":"$timeseries.t", "v":"$timeseries.v", "_id":0, "locationId":"$locationId", "forecastTime":"$forecastTime"}}
])
db.subscriptions.aggregate([ { "$match": { "$expr": { "$gte": [ "$timeseries.t", "$forecastTime" ] } } } ])
#for r in it:
        #print(f"{r['locationId']},{r['forecastTime']},{r['t']},{r['v']}")

In [ ]:

collection = db["SimulatedForecastingScalarTimeSeries"]
it = collection.aggregate([
    {"$match": {"parameterId":"QR", 
                "moduleInstanceId": {"$in": ["ADJUSTQ_ALCT1_Forecast","ADJUSTQ_ARTT1_Forecast","ADJUSTQ_AVLN7_Forecast","ADJUSTQ_BARK2E_Forecast","ADJUSTQ_BIGT1_Forecast","ADJUSTQ_BIRN7_Forecast","ADJUSTQ_BLAN7_Forecast","ADJUSTQ_BLTN7_Forecast","ADJUSTQ_BNAA1_Forecast","ADJUSTQ_BRRT1_Forecast","ADJUSTQ_BRVG1_Forecast","ADJUSTQ_BSBA1_Forecast","ADJUSTQ_CAFT1_Forecast","ADJUSTQ_CDZK2_Forecast","ADJUSTQ_CEPN7_Forecast","ADJUSTQ_CHKT1_Forecast","ADJUSTQ_CHSA1_Forecast","ADJUSTQ_CKVT1N_Forecast","ADJUSTQ_CLVV2_Forecast","ADJUSTQ_CNVT1_Forecast","ADJUSTQ_COLT1_Forecast","ADJUSTQ_CTPN7_Forecast","ADJUSTQ_DOET1_Forecast","ADJUSTQ_EMBT1_Forecast","ADJUSTQ_EMGT1_Forecast","ADJUSTQ_ENGG1_Forecast","ADJUSTQ_FLCN7_Forecast","ADJUSTQ_FLTT1_Forecast","ADJUSTQ_FYTT1_Forecast","ADJUSTQ_GATV2_Forecast","ADJUSTQ_GERA1_Forecast","ADJUSTQ_HEPN7_Forecast","ADJUSTQ_HMLT1_Forecast","ADJUSTQ_HORT1_Forecast","ADJUSTQ_HSPN7_Forecast","ADJUSTQ_HWEG1_Forecast","ADJUSTQ_IRCT1_Forecast","ADJUSTQ_IVYN7_Forecast","ADJUSTQ_JNSV2_Forecast","ADJUSTQ_LBVT1_Forecast","ADJUSTQ_LLDT1_Forecast","ADJUSTQ_MARN7_Forecast","ADJUSTQ_MCGT1_Forecast","ADJUSTQ_MCST1_Forecast","ADJUSTQ_MLTT1_Forecast","ADJUSTQ_MYVT1_Forecast","ADJUSTQ_NEEN7_Forecast","ADJUSTQ_NOLT1_Forecast","ADJUSTQ_NRMT1_Forecast","ADJUSTQ_NWPT1_Forecast","ADJUSTQ_OAKT1_Forecast","ADJUSTQ_PLKT1_Forecast","ADJUSTQ_PORT1S_Forecast","ADJUSTQ_PORT1_Forecast","ADJUSTQ_PRTN7_Forecast","ADJUSTQ_PSPT1_Forecast","ADJUSTQ_RLRV2_Forecast","ADJUSTQ_ROSN7_Forecast","ADJUSTQ_RTRN7_Forecast","ADJUSTQ_SALV2_Forecast","ADJUSTQ_SEET1_Forecast","ADJUSTQ_SEVT1_Forecast","ADJUSTQ_SFYV2_Forecast","ADJUSTQ_SGWN7_Forecast","ADJUSTQ_SHVT1_Forecast","ADJUSTQ_SMFV2_Forecast","ADJUSTQ_TAZT1_Forecast","ADJUSTQ_TLRT1_Forecast","ADJUSTQ_TMFT1_Forecast","ADJUSTQ_TWNT1_Forecast","ADJUSTQ_VSTV2_Forecast","ADJUSTQ_WCKG1_Forecast","ADJUSTQ_WDVA1_Forecast","ADJUSTQ_WHTT1_Forecast"]},
                "locationId":{"$in":["SMFV2","SALV2","RLRV2","GATV2","CLVV2","VSTV2","SGWN7"]},
                "encodedTimeStepId":"DTOD_0_6_12_18TZ_CST", "qualifierId":"[\"Adj\"]"}
    },
    {"$sort":{"locationId":1, "forecastTime":1,}},
    {"$unwind" : "$timeseries"},
    { "$match": { "$expr": { "$gte": [ "$timeseries.t", "$forecastTime" ] } } },
    {"$match" : {"$expr" : { "$lte" : [{"$dateDiff" : {"startDate":"$forecastTime", "endDate":"$timeseries.t", "unit":"hour"}}, 168]}}}, 
    {"$project" : {"t":"$timeseries.t", "v":"$timeseries.v", "_id":0, "locationId":"$locationId", "forecastTime":"$forecastTime"}}
])
db.subscriptions.aggregate([ { "$match": { "$expr": { "$gte": [ "$timeseries.t", "$forecastTime" ] } } } ])

In [132]:
def to_cardinal_time(t, time_step_minutes):
	date = datetime(t.year, t.month, t.day)
	minutes = t.hour * 60 + t.minute
	remainder = minutes % time_step_minutes
	if remainder > 0:
		minutes += time_step_minutes - remainder if remainder * 2 >= time_step_minutes else -remainder
	return date + timedelta(minutes=minutes)

In [133]:

data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Paris', 'London']
}

df = pd.DataFrame(data)
df

      Name  Age      City
0    Alice   25  New York
1      Bob   30     Paris
2  Charlie   35    London